services: 
  donwok:
    build:
      context: .
      dockerfile: Dockerfile.donwok
    volumes:
      - ./local/donwoks:/var/www/html/donwoks:cached
    restart: unless-stopped
    networks:
      - proxy-net
    ports:
      - 80:80

networks:
  proxy-net:
    external: true